name: Hosting GLPI on AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write 
  contents: read 

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: ./docker
    
    steps:
      - name: Git clone the repo
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::566027688242:role/GitHubOIDCRole
          aws-region: ${{ vars.REGION}}
      
      - name: Sts GetCallerIdentity
        run: |
          aws s3 ls

      - name: create tfstate bucket
        run: aws s3 mb s3://${{ vars.TFBUCKET }}
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TFBUCKET }}" \
            -backend-config="region=${{ vars.REGION }}" \
            -backend-config="key=terraform.tfstate"
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply --auto-approve

      # run terraform