name: Spin Up

on:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read 

jobs:
  spin-up:
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Git clone the repo
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::566027688242:role/GitHubOIDCRole
          aws-region: ${{ vars.REGION}}

      - name: create tfstate bucket
        run: aws s3 mb s3://${{ vars.TFBUCKET }}
        continue-on-error: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TFBUCKET }}" \
            -backend-config="region=${{ vars.REGION }}" \
            -backend-config="key=terraform.tfstate"
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: cp key to s3
        if: ${{ vars.KEYNAME != '' }} 
        run: |
          aws s3 cp ./glpi-key.pem s3://${{. vars.TFBUCKET }}/glpi-key.pem